### ISSUE TITLE
Bug: handle for undefined address

### ISSUE THREAD

**Issue by jpremo** [Code-the-Dream-School/bb-practicum-team-1-back#72]
Entering an address of just one letter for signup results in an error. `Cannot destructure property 'latitude' of '(intermediate value)' as it is undefined.`

Let's make it so that if the address is undefined we return a sample lat/lon with the expected data format. Will require editing of addressToCoordinate.

Also account for data not being an array like we want. Return a similar sample lat/lon. I would suggest the sample lat/lon to be in one of the cities the seed data references.

**Comment by larasodjati** [comment]
Hi Jacob, please specify what you mean by **returning a sample lat/lon with the expected data format.**, as far as I remember during the meeting we needed to modify something in our signup controller instead of addressToCoordinate function, if so would it look like below? 

And for **account for data not being an array like we want. Return a similar sample lat/lon.** Does it mean we expect an array instead of an object for this?  Thank you!

```
const latitude = 40.6390599
const longitude = -73.6398912

const signUp = async (req, res) => {
    const userAddress = req.body.address
    if (!userAddress){
        res.status(StatusCodes.BAD_REQUEST).json(coordinate that we declare above?)
    }
    const { latitude, longitude, address } = await addressToCoordinate(
        userAddress
    )
    const user = await User.create({
        ...req.body,
        latitude,
        longitude,
        address,
    })
    const token = user.createJWT()

    res.status(StatusCodes.CREATED).json({
        user: {
            email: user.email,
            username: user.username,
            givenName: user.givenName,
            familyName: user.familyName,
            dateOfBirth: user.dateOfBirth,
            address: user.address,
            latitude: user.latitude,
            longitude: user.longitude,
        },
        token,
    })
}
```
